### ISSUE TITLE
Scroll bars are subject to content dragging

### ISSUE THREAD

**Issue by tturini** [Xanthos-Eve/vintel#101]
vertically is ok
instead, the orizzontal at the bottom (usefull for provi+catch zone) it's inverted, when mouse goes into right, the diagram goes into left :)
OS: win10 1115 updated

EDIT: i'm wrong, the bottom bar, I can see it, but does not exist, and work drag and drop on background image)

PS: great program :)

**Comment by Xanthos-Eve** [comment]
I see - my recent change to drag the content seems to also apply to the scroll bars. Will be fixed in the next build.
