### ISSUE TITLE
Compile error - no webkit.

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#104]
Getting my virtual environment set up with everything needed for QT5. I am seeing the following in the console.  I have QT 5.5.1 installed. @3vi1 How did you get around this?

  File "/Users/mark/code/vintel/src/vi/ui/viui.py", line 36, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage
ImportError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by 3vi1** [comment]
Which distro are you running?

If it's Ubuntu, have you run 'sudo apt install python-pyqt5.webkit python3-pyqt5.qtwebkit'?  That will install both the python2 and python3 bindings.

**Comment by Xanthos-Eve** [comment]
I'm on OS X so I used brew install pyqt5.

**Comment by Xanthos-Eve** [comment]
We need to have a set of platform independent steps to add to the readme so that anyone on any platform can install and build. I'm considering keeping the requirements simple by cutting over to PyQt5.QtWebEngineWidgets. Thoughts?

**Comment by 3vi1** [comment]
Unfortunately, that's not packaged for Debian or any of it's derivatives (Ubuntu included):  https://askubuntu.com/questions/763612/importerror-no-module-named-pyqt5-qtwebenginewidgets

I think most Linux users would be comfortable running it straight from source.  There are only a few packages to install, but I could probably spin up some VMs and document the steps for a couple of the more popular distros.

**Comment by Xanthos-Eve** [comment]
For Linux running from source is fine as long as they are able to easily
follow our requirements and get all the dependencies. Just need to make
sure we are covered on Mac and Win7 for the readme

**Comment by Xanthos-Eve** [comment]
I have gotten past this.
