### ISSUE TITLE
Parsing Improvement - "____ gate"

### ISSUE THREAD

**Issue by 3vi1** [Xanthos-Eve/vintel#106]
Currently, messages like "Player > XHQ-7V reds camping on JEIVE gate" are making the adjacent system the gate leads to (JEIV-E in this example) red.  

We should probably set it to ignore systems when the next word is "gate" so that it doesn't trip distance alarms unnecessarily.

**Comment by Xanthos-Eve** [comment]
+1

**Comment by 3vi1** [comment]
I'll see about making a patch for it now... It's too dangerous ATM to leave station with reds picking on us poor newbie miners.  :)

Also, I'll make sure it doesn't misinterpet/ignore "SYSTEM gate to ___ bubbled" type message.

**Comment by Xanthos-Eve** [comment]
Until we have a stable build on develop we should probably march ahead with
these kinds of changes on master and then I'll cherry pick / merge to
develop

**Comment by 3vi1** [comment]
Will do.  I have it working, but I'd like to QA it for a few hours before I submit the patch.  Will have it headed your way tomorrow.

**Comment by 3vi1** [comment]
Submitted https://github.com/Xanthos-Eve/vintel/pull/108/commits/7e59147b1095c59f5d25618c5a7e430a5b09af60
