### ISSUE TITLE
Port QWebView and Friends to QWebEngineView, etc.

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#107]
QWebView has been deprecated. Keeping it simple with less requirements - the best approach seems to be to port to the new module.

**Comment by Xanthos-Eve** [comment]
I am setting the content with QWebEngineView.setHtml and the performance is abysmal. Big flash everytime the content is updated.

**Comment by Xanthos-Eve** [comment]
@3vi1 I am preparing to commit changes for this. Warning: performance on QWebViewEngine classes is really bad.

I would like to ask you to make changes to support both - or at least come up with a plan that we can execute together. Since I don't have your set up with the ubuntu packing (with QWebView) I think it would be better for you to see how we would "ifdef" this based on six.PY2 like we do in cache.py. With the ifdef in place we should be able to set up the branch so we can both play there. Let me know your thoughts please.

**Comment by 3vi1** [comment]
Okay, I'll take a look at it when you have committed your changes.

**Comment by Xanthos-Eve** [comment]
Great, thanks! I think I have most everything set up for you - will need a bit of testing and maybe some refactor on your part.

**Comment by Xanthos-Eve** [comment]
Leaving this open until both QWebView and QWebEngineView are supported.

**Comment by 3vi1** [comment]
Pull Request submitted!  :)  https://github.com/Xanthos-Eve/vintel/pull/114

**Comment by Xanthos-Eve** [comment]
Yay! Closing
