### ISSUE TITLE
Can't see info...

### ISSUE THREAD

**Issue by workingz** [Xanthos-Eve/vintel#112]
Can't see any text wt? http://imgur.com/zlW3NOk

**Comment by Xanthos-Eve** [comment]
@workingz does this happen with multiple systems? On multiple maps? Or is it a specific system?

**Comment by workingz** [comment]
on all maps... sometime text appears but after some minutes again disappear

**Comment by Xanthos-Eve** [comment]
What version of windows?

**Comment by workingz** [comment]
7 win

**Comment by Xanthos-Eve** [comment]
Do you belong to any intel channels? Have you entered any of those into the settings? Is your eve client open?

**Comment by workingz** [comment]
all channels is default http://imgur.com/3gp8Upe

**Comment by workingz** [comment]
yes Im in game

**Comment by workingz** [comment]
I don't know why it's happened. Now this bug in all version Vintel. Before everything worked fine

**Comment by Xanthos-Eve** [comment]
On the Kos Menu - is Scan Intel for Requests checked?

**Comment by workingz** [comment]
As you can see on screenshot http://imgur.com/3gp8Upe all is ON

**Comment by Xanthos-Eve** [comment]
Anything interesting in the output.log file?

**Comment by workingz** [comment]
I don't know about what you're talking

**Comment by Xanthos-Eve** [comment]
Inside your eve folder, there is a vintel folder, and inside there is a log folder with one or more log files. Copy the newest one here if you can.

**Comment by workingz** [comment]
[output.txt](https://github.com/Xanthos-Eve/vintel/files/354265/output.txt)

**Comment by Xanthos-Eve** [comment]
This helps. Is your system memory constrained?

**Comment by Xanthos-Eve** [comment]
So far I have not figured out how this widget is deleted except that we keep a list of chat widgets that each chat should appear in - we may be dropping it from this list?

**Comment by workingz** [comment]
so I don't understand, what should I do?

**Comment by workingz** [comment]
What's wrong in output.txt ?

**Comment by Xanthos-Eve** [comment]
The parser is trying to access QLabel but the widget has been deleted - no
one else seeing this that I know of - I was unable to reproduce. You will
have to wait until we can find and fix the issue.

**Comment by workingz** [comment]
ok. understand, thank you!

**Comment by Xanthos-Code** [comment]
The comment above "I don't know why it's happened. Now this bug in all version Vintel. Before everything worked fine" indicates to me that this is a system problem and not an app problem. If the behavior of older versions of the app, running on your system, have changed then the most likely culprit is outside of the app.
