### ISSUE TITLE
Map is not scrolling from code due to API change converting from QT4 -> QT5

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#116]

**Comment by Xanthos-Eve** [comment]
Pretty weird that the scrollPosition and getScrollPostion are no longer exposed in QWebEngine classes like they were for QWebView classes.

**Comment by 3vi1** [comment]
More of a QWebEngine issue than Qt4-> Qt5, eh?  Dragging the map around still works for me in QWebView.

**Comment by m4rkk** [comment]
Yeah - I can move the scroll with javascript, just dont know how to track changes to the scroll.

**Comment by 3vi1** [comment]
Related:  https://github.com/Xanthos-Eve/vintel/pull/117
