### ISSUE TITLE
Win 10 - Vintel always on top.

### ISSUE THREAD

**Issue by Tyaak** [Xanthos-Eve/vintel#120]
I am not sure if it is known already, but I updated to win10 yesterday and since that update only vintel stays on top at all times. I can't even access the taskbar as it pops up under vintel. I tried fixing it through win10 but to no avail. So i thought I should post here. I have a dual monitor set up with just my game playing on the main screen and everything else on the second. I usually have vintel up 95% of the time on the second monitor and with win7 vintel reacted like all other programs. I am using v1.2.3 I would also like to note that Vintel stays on top of ALL windows on my second monitor. I am having to minimize Vintel to see any other window.

**Comment by Xanthos-Eve** [comment]
Win 10 has its own set of problems - I remind on Win7. I have not heard of
anyone else with this issue. There is a setting to keep the app up at all
times - have you played with those window settings? Maybe it got flipped by
accident.

**Comment by Xanthos-Eve** [comment]
I remain not remind =)
