### ISSUE TITLE
Investigate polling the clipboard

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#29]
Let's see if we can do this without impacting performance a whole lot. Testing and research reveals that you cannot get clipboard change notifications sent to your app when it is in the background (on OS X at least).

**Comment by superandoni** [comment]
Is this currently coded in 1.0? Because I sometimes randomly get notifications from Vintel.

**Comment by Xanthos-Eve** [comment]
No it is not.
