### ISSUE TITLE
Assess performance on Win32

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#35]
I just tweaked the intervals for timers and threads in the app. This took it from 40-90% cpu to 4-25% utilization. Can you please do an assessment on the pc and see how we look there as far as average utilization. I'd like to make sure that the utilization is still reasonable on a different platform.

**Comment by superandoni** [comment]
Seems fine, under 10% CPU load in Windows 7 (i5-3570 cpu), with no apparent spikes and about 106 MB of RAM consumption with very minor increments over time. Maybe we could try profiling tools?
