### ISSUE TITLE
User reports that audio only works for admin on Win32

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#37]
running as a normal user apparently sound cannot be heard.

**Comment by Xanthos-Eve** [comment]
Please investigate and see if we can find a solution. I think most people run in admin but its not a good practice and if we can support non-priveldge user mode we should.

**Comment by superandoni** [comment]
User's system specifications: http://sytrep.com/eve/dxdiag.txt

**Comment by Xanthos-Eve** [comment]
Not affecting other users.
