### ISSUE TITLE
System update timer not correct

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#39]
Just noticed it, the little update timer for the systems who are mentioned somewhere in intel is not always correct.

First of all, it only updated the timer every 3 or 4 seconds, not as expected every second, which leads to a little offset in these timers.

Example:
System A and System B got mentioned in intel, both systems are marked in the map and have a little timer, 0 sec. after a while these timers are updating to 3 or 4 seconds and so on. Some time later, both systems no longer mentioned in intel, there is an offset between both timers, System a is at 5m 15s and System B at 5m 17s.

A bit confusing.

**Comment by Xanthos-Eve** [comment]
Hmm, this was probably introduced by me recently - the map used to update once a second but performance was poor so I backed it off a bit. The timers should not rely on the update interval - we can probably set timers for these and have them update the map when the timer expires making sure another  timer is not updating at the same time.

Definitely not a simple change.

**Comment by Xanthos-Eve** [comment]
If the offset is small I think we can live with this. It comes with the benefit of improved app performance and less system load. Polling every second is just too processor intensive. If you disagree please reopen this issue,
