### ISSUE TITLE
No Sound on Linux

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#40]
Testsound in Sound Settings doesn't work at all. No idea if sound in general works, but didn't hear anything so far.

» Linux System
» Pulseaudio
» VLC sound backend

**Comment by chriz3W** [comment]
Testsound works on win10 for me

/chriz

**Comment by ppfeufer** [comment]
Haha, can be closed, pyglet was not installed.

This may also be the issue for some windows user who don't hear any sound?

**Comment by Xanthos-Eve** [comment]
Good point, I will update the faq if there is not already an article there.
