### ISSUE TITLE
Tray Icon missing?

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#42]
System Tray Icon missing?
![screenie_118](https://cloud.githubusercontent.com/assets/2989985/12532633/f126f454-c218-11e5-9a00-065eabc3caef.png)

**Comment by Xanthos-Eve** [comment]
@ppfeufer can you report this? what are the steps? What platform?

**Comment by ppfeufer** [comment]
Linux
KDE

Starting the application, no tray icon ...

**Comment by superandoni** [comment]
Tray icon does show in Windows 7

**Comment by Xanthos-Eve** [comment]
Anyone else want this - I'm on a Mac

**Comment by Xanthos-Eve** [comment]
Also, Notification emergent bubble shows up in Windows 7 for all cases except when system alarm.

**Comment by Xanthos-Eve** [comment]
I'm running Windows 7 now. I see the try icon.

**Comment by ppfeufer** [comment]
Still missing for me ....

**Comment by Xanthos-Eve** [comment]
Well were going to need someone who can code in python on a Linux box to look into this. Anyone?

**Comment by 3vi1** [comment]
It may be fixed with the move to Qt5.  At least, the tray icon works on Unity now.  I'll test it with KDE when I get home tonight and send you a pull request for develop tomorrow.

**Comment by 3vi1** [comment]
I managed to steal a few minutes at lunch to test, and the Qt5 tray icon does work with KDE (http://storage1.static.itmages.com/i/16/0629/h_1467220054_3455582_bdc3f4923a.png).  I'll finish my QA checks tonight.

**Comment by Xanthos-Eve** [comment]
@ppfeufer Not 100% sure on this but I did find problems whereby we were allocating the tray icon 3 times. Once is enough! Reopen if you still see issues.

**Comment by ppfeufer** [comment]
Just updated and still no tray icon

> python2.7 vintel.py /home/ppfeufer/documents/EVE/logs/Chatlogs/
> 07/04 07:29:59| 
> 07/04 07:29:59| ------------------- Vintel 1.2.3 starting up -------------------
> 07/04 07:29:59| 
> 07/04 07:30:00| Load jump bridges
> 07/04 07:30:00| Creating chat parser
> 07/04 07:30:00| Initializing contextual menus
> 07/04 07:30:00| Updating the map
> 07/04 07:30:00| Map setup complete

is all I get in console when starting Vintel

**Comment by 3vi1** [comment]
@ppfeufer:  Do you have sni-qt installed?

1.2.3 is still using the old Qt4 libraries.  Newer KDE requires sni-qt for tray support with Qt4.  Qt5 won't be used until the develop release gets stabilized, at which time you won't need sni-qt.

**Comment by ppfeufer** [comment]
Yes, it is installed.
