### ISSUE TITLE
Sound remains active

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#46]
... even if it should be not active (see screenshot)

![screenie_123](https://cloud.githubusercontent.com/assets/2989985/12539180/d41b5ff6-c2ec-11e5-8998-2de08e16c5f6.png)

Plattform: Linux

**Comment by ppfeufer** [comment]
It seems after a complete system restart the sound is according to it's setting. At least for the active/non active state. Which seems a bit weird to me, because simply closing and starting the application again didn't help at all.

**Comment by superandoni** [comment]
Fixed, variable wasn't being checked in playSound.
