### ISSUE TITLE
Jump bridges, current location do not render correctly on the combined map

### ISSUE THREAD

**Issue by Drix1** [Xanthos-Eve/vintel#51]
![vintel buggy](https://cloud.githubusercontent.com/assets/7212843/12602436/a28a43ee-c4a9-11e5-98a5-b4ee6b41fe5b.png)

seems like the alignment is off some how

**Comment by Xanthos-Eve** [comment]
Yes, this is due to a bug in merging the two maps and will be fixed in the next release.

**Comment by Xanthos-Eve** [comment]
To create this map - the two maps were joined and overlapping systems were moved by adding a transform to each system - the transform is used when the entities are being layed out. The trick will be to take the transform into account when laying out the JBs and Current Location.

**Comment by Xanthos-Eve** [comment]
Yes when the two maps were overplayed a transform was placed on the catch
systems so they can all be offset and not on top of provi systems. It looks
like placement of the job is using the wrong offset or not using the
transform.

**Comment by Xanthos-Eve** [comment]
Happy to be closing this one. Map was regenerated and transforms added, etc. Then the code was adjusted to take the transforms into consideration when laying out the annotations on the map.
