### ISSUE TITLE
Simplify configuration with a setup window

### ISSUE THREAD

**Issue by superandoni** [Xanthos-Eve/vintel#52]
A few users have reported hard to find features such as alarm distance. Maybe sound and these other options could be centralized in a single config window.

**Comment by Xanthos-Eve** [comment]
Good call.

**Comment by ppfeufer** [comment]
Maybe as a tabbed window. A tab for every category, like ...
General | Audio | Map | Chat | KOS Check

To keep it neatly arranged.

**Comment by Xanthos-Eve** [comment]
Sections maybe - not sure that we have enough settings to warrant tabs.

**Comment by Xanthos-Eve** [comment]
Moving to the wiki for ideation
