### ISSUE TITLE
(Idea) Jump Bridge Owner Information

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#55]
It would be nice to see which alliance owns a Jump Bridge, would make the life of FCs a bit easier and maybe preventing fleet members from getting killed on a JB tower if they don't have standings with the owner.

Usually the JB owner is also the system holder's alliance, so this data should be available on dotlan.

**Comment by superandoni** [comment]
That would be good, however the jumpbridge information is currently pulled via text file (example: http://sytrep.com/eve/JumpBridge.txt ). We either add owner info to the txt and use it in Vintel coding in the required parsing, or we go to dotlan to pull the owner info.

**Comment by Xanthos-Eve** [comment]
I would like to see the planet / moon for each jb as well. We should plan to look to dotlan for any JB format they may have and adopt that to replace our text format.

**Comment by Xanthos-Eve** [comment]
We need to look to dotlan for any jump bridge xml format they support and use that.

**Comment by Xanthos-Eve** [comment]
Dupe
