### ISSUE TITLE
Adjust xxx KOS check detection

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#56]
Example from intel:
[18:02:47] Zelyxoo Omega > > xXx Vice F-YH5B

What Vintel did:
![screenie_168](https://cloud.githubusercontent.com/assets/2989985/12894439/fbdaccf6-ce96-11e5-9523-775d94cf1a77.png)

Short explanation:
**xXx Vice** is actually a pilot » http://evewho.com/pilot/xXx+Vice

Unfortunately there is no way to detect linked names in log files, because CCP has filtered out there mark up. A possible way would be to make sure the KOS check only gets triggered with "xxx" instead of "xXx". So trigger only with lowercase letters.

Another solution would be to exclude thhe monitored intel channels from KOS checking at all.

**Comment by Xanthos-Eve** [comment]
I like the idea of excluding the monitored chat channels, from kos checking - no one wants to see the xxx in intel channels. Case check may be tricky as I think we upper case everything for string compare readiness. I guess it will only come up in fleet and private chat then...
