### ISSUE TITLE
.gitignore collides with repository layout

### ISSUE THREAD

**Issue by Xaroth** [Xanthos-Eve/vintel#58]
.gitignore states to ignore the .idea directory, but it is currently checked in, which may cause issues.

I would also recommend using the 'standard' python gitignore rules that github maintains, they should catch most (if not all) other corner cases of files that you don't want checked in: https://github.com/github/gitignore

**Comment by Xanthos-Eve** [comment]
Now ignoring only the workspace.xml. There were a lot of things in the recommended gitignore and some that we need to commit (.spec) so I didn't go do much with the gitignore.
