### ISSUE TITLE
Some channels are not being scanned

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#59]
User claims that some are and some are not scanned for him. Examples of channels not scanned: "B-F1 sec" and "g.sec"

**Comment by Xanthos-Eve** [comment]
This was reported to me by someone in game - I have not seen this happen. Anyone else?

**Comment by ppfeufer** [comment]
Nope, all fine. Maybe he didn't add the channels to the monitored list properly?

**Comment by marivx** [comment]
i insert well the chat but some of them not work

**Comment by marivx** [comment]
i try again but not work

**Comment by Xanthos-Eve** [comment]
Please list here the names of any channels you have tried @marivx - I'm wondering if the format of the name is the issue. Also what operating system and version are you on and what region / language is your computer set for?

**Comment by marivx** [comment]
gc.sec  ,  B-F1 sek


Il 03 Marzo 2016 20:51:29 Xanthos-Eve <notifications@github.com> ha scritto:

**Comment by Xanthos-Eve** [comment]
Closing as not a bug. Here's what I did to verify this - created a channel "xxx.x" and added it to the intel channels. I then reported a reported a red in a system and saw the report in the All Intel panel of the main window.

**Comment by marivx** [comment]
At me and My Friend not work


Il 05 Marzo 2016 20:49:43 Xanthos-Eve <notifications@github.com> ha scritto:

**Comment by Kalle002** [comment]
It doesnt seem to be the format.
"gc.test" does work while "gc.sec" does not.
