### ISSUE TITLE
Need text to speech on non OS X platforms

### ISSUE THREAD

**Issue by Xanthos-Eve** [Xanthos-Eve/vintel#6]
gTTS looks great but google locks down the api from time-to-time so its not reliable.

**Comment by XanthosX** [comment]
https://pythonspot.com/speech-engines-with-python-tutorial/

**Comment by XanthosX** [comment]
Tried googleTTS - it is throttled so you need a key and you get a couple hundred requests a day.
Tried voiceRss - robot like speech on their web site duo page. I got a 404 using the API

**Comment by XanthosX** [comment]
google_speech looks nice - just requires installing a bunch of stuff

**Comment by XanthosX** [comment]
Another option - have users sign up and get an api key for google - then they can use their own service plan.

**Comment by PageArkanis** [comment]
You could use https://pypi.python.org/pypi/SpeechRecognition 
Is pure Python and does not need extra install stuff and can use google speech.

**Comment by PageArkanis** [comment]
You could use https://github.com/marytts/marytts. Easy to install and easy to use TTS.

**Comment by Xanthos-Eve** [comment]
Excellent suggestion! I will give it a go.

**Comment by 3vi1** [comment]
What do you think about pyFestival?  https://pypi.python.org/pypi/pyfestival/?

**Comment by Xanthos-Eve** [comment]
Interesting, though the manual has a broken link. We are moving to python 3
and QT 5 now - may have more options with that mix.

**Comment by 3vi1** [comment]
I haven't really had time to look at the api, but I have played with festival in the past so it was the first thing that came to mind.  I'm willing to help out from the Linux side of things - I'll try to familiarize myself with what you're already doing on OSX when I get the time.

**Comment by 3vi1** [comment]
I thought I found an easy solution in the pyttsx package, but as it turns out... not only is the speech quality much like a speak n' spell (like Festival if you don't install a higher quality voice), but it only works with Python2.  Too bad, because it was literally 2 minutes to implement.

Let me continue looking at other options.  I will try pyfestival if I don't find something better first.

**Comment by 3vi1** [comment]
nm.... with the high quality voice I have in festival, pyfestival sounds great!  I'll make a develop-based patch and send it your way tomorrow.  We can apply it to master if you want to push it out sooner.  Since I can only use PyQt5 on Linux,  I actually do all my dev on the develop branch.

**Comment by 3vi1** [comment]
Hey, am I crazy or is the voice not wired up to anything yet?  I guess I was expecting there to be code somewhere that said things when on OSX, but maybe you just haven't added it until you had a cross-platform solution?

I've added a "Test Voice" button to the sound dialog to test it for now.  I left the code such that it will prefer darwinSpeak if you're on OSX - but we can change that if you like.  Will send you a pull request to look over when I get home tonight.

**Comment by 3vi1** [comment]
https://github.com/Xanthos-Eve/vintel/pull/110

**Comment by Xanthos-Eve** [comment]
OSX has native support so its easy there - once we have a cross platform
module we can refactor the code as needed. I looked at festival and thought
it was overkill for what we are doing.
