### ISSUE TITLE
(Snapshot Version) Avatars in Chat stop working after a while

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#62]
Just trying the 1.1.0 Snapshot and the avatars in chat stop working after a while.

![screenie_233](https://cloud.githubusercontent.com/assets/2989985/13554593/612cebaa-e3ac-11e5-8cd1-79c20af75187.png)

**Comment by Xanthos-Eve** [comment]
Please check your app logs. There is a print statement in AvatarFindThread: "An error in the AvatarFindThread : {0}". The {0} part will be filled in with the reason for the failure.

Also, I wonder if this ever resolved itself. A lot of those chat entries came in pretty close to one another.

**Comment by ppfeufer** [comment]
Where do I find these logs?

**Comment by Xanthos-Eve** [comment]
I'll close it then - was not able to report.

**Comment by Xanthos-Eve** [comment]
Well it appears that our logging strategy was poor. I have just implemented proper logging on the development branch logs live in the same place as the intel cache. Next to your EVE chat logs.
