### ISSUE TITLE
Alarm Sound do not works on my Ubuntu

### ISSUE THREAD

**Issue by StefanoMad** [Xanthos-Eve/vintel#63]
when i launch Vintel from Command Line i get this:

"sni-qt/2645" WARN  20:34:59.441 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 

Then Vintel opens and if i do a CTRL+A+C+C it checks local for koses but i do not get the alarm sound on proximity and eve on sound test
old Vintel 0.62 was and still works

**Comment by StefanoMad** [comment]
Got it working reinstalling pyglet trought pip

**Comment by Xanthos-Eve** [comment]
The library Vintel uses to play sound has changed with 1.0.0 and up. You
are probably missing Pyglet 1.2.4. Just get that and try to run. From the
readme:

To run or build from the source you need the following packages:


   - Python 2.7.x https://www.python.org/downloads/ Vintel is not
   compatible with Python 3!
   - PyQt4x http://www.riverbankcomputing.com/software/pyqt/download Please
   use the PyQt Binary Package for Py2.7 Vintel is not compatible with PyQt5!
   - BeautifulSoup 4 https://pypi.python.org/pypi/beautifulsoup4
   - Pyglet 1.2.4 (for python 2.7)
   https://bitbucket.org/pyglet/pyglet/wiki/Download pyglet is used to play
   the sound – If it is not available the sound option will be disabled.
