### ISSUE TITLE
some channels on autoblock?

### ISSUE THREAD

**Issue by Kalle002** [Xanthos-Eve/vintel#64]
This problem was reported earlier but marked as solved / closed

The channel "gc.sec" is not scanned by Vintel.

I made a few tests myself to check if there was a problem with the dot in the channel name.
The result was:
"gc.test" worked normally.
"gc.sec" was not scanned.

I tested this on 3 different windows 7 machines ... with lots of different versions of vintel, up to the 1.0.0 version.
It never worked.

If you could fix it somehow, it d be great.

**Comment by Xanthos-Eve** [comment]
If you can give me access to "gc.sec" I will look into it.
