### ISSUE TITLE
Fatal error: vintel returned -1

### ISSUE THREAD

**Issue by Enumeration** [Xanthos-Eve/vintel#65]
Hi,

I encountered this error today. I had two eve clients open when it happened, one in character select screen and the other with a logged in character, on a W10 x64 PC. This issue first occurred with Vintel 1.0.

When using Vintel 1.0, the "error.log"-file in the "%USERPROFILE%\Documents\EVE\vintel"-folder states:
```
--------------------------------------------------------------------------------
2016-03-13, 15:34:41
--------------------------------------------------------------------------------
<type 'exceptions.IndexError'>: 
list index out of range
--------------------------------------------------------------------------------
  File "<string>", line 118, in <module>
  File "src\vi\ui\viui.py", line 138, in __init__
  File "src\vi\ui\viui.py", line 184, in setupMap
  File "src\vi\dotlan.py", line 96, in __init__
  File "src\vi\dotlan.py", line 129, in _prepareSvg
1.0.0
```

When using Vintel 1.1, the "output.log"-file in the "%USERPROFILE%\Documents\EVE\vintel\logs"-folder states:
```
03/13 03:57:29| 
03/13 03:57:29| -------------- Vintel 1.1.0 starting up --------------
03/13 03:57:29| 
03/13 03:57:29| 'MainWindow' object has no attribute 'changeClipboard'
03/13 03:57:29| 'MainWindow' object has no attribute 'changeFloatingOverview'
03/13 03:57:29| 'MainWindow' object has no attribute 'changeAlreadyShowedSoundWarning'
03/13 03:57:29| Finding map file
03/13 03:57:29| <
t
y
p
e
 
'
e
x
c
e
p
t
i
o
n
s
.
I
n
d
e
x
E
r
r
o
r
'
>
:
 


l
i
s
t
 
i
n
d
e
x
 
o
u
t
 
o
f
 
r
a
n
g
e
None
```

After removing the "%USERPROFILE%\Documents\EVE\vintel"-folder the program worked again.

Best regards,

Enum

**Comment by Xanthos-Eve** [comment]
These are harmless - just some settings that were removed and just  warning when trying to load them

03/13 03:57:29| 'MainWindow' object has no attribute 'changeClipboard'
03/13 03:57:29| 'MainWindow' object has no attribute 'changeFloatingOverview'
03/13 03:57:29| 'MainWindow' object has no attribute 'changeAlreadyShowedSoundWarning'


list index out of range is something new - good call on removing the cache

**Comment by Enumeration** [comment]
I can send you a backup of the faulty cache, if you need it for your investigation.

**Comment by Xanthos-Eve** [comment]
File "src\vi\dotlan.py", line 129, in _prepareSvg

That line is trying to read into the svg map file. Not sure why removing the cache would resolve this.

**Comment by Enumeration** [comment]
Couldn't upload the zip file to GitHub for some reason. Here is the WeTransfer link: 
http://we.tl/P6VpoiOjRJ

**Comment by Xanthos-Eve** [comment]
Thanks!

**Comment by Xanthos-Eve** [comment]
Tried running with that cache - it had no region set so it went to the network to get the default map Providence.svg. Everything worked as expected.
