### ISSUE TITLE
No Avatar pictures and clipboard KOS-heck Error

### ISSUE THREAD

**Issue by RickTalven** [Xanthos-Eve/vintel#66]
Just as i said. I don't get any Avatar portraits and the VIntel Logo for KOS checks needs quite some time to load.

In addition, there should be a feature for KOS checks with the clipboard. That doesn't work, i just get:
"Error in KOSCheckerThread: not all arguments converted during string formatting"

Here's the Error log for you. I hope that helps.
[output.txt](https://github.com/Xanthos-Eve/vintel/files/171071/output.txt)

**Comment by Xanthos-Eve** [comment]
Is this from the official 1.1.0 Release build or are you running from a branch? I ask because the code that drops output.txt was never released. Try with the 1.1.0 Release.

**Comment by Xanthos-Eve** [comment]
https://github.com/Xanthos-Eve/vintel/releases/tag/1.1.0

**Comment by Xanthos-Eve** [comment]
Seeing this now myself

**Comment by Xanthos-Eve** [comment]
Fixed
