### ISSUE TITLE
-- Unhandled Exception -- ... in <module> mainWindow

### ISSUE THREAD

**Issue by Tetractys** [Xanthos-Eve/vintel#67]
hi!
i'm on Linux ubuntu 15.10 64bit with both python 2.x and 3.x installed both last packed version.
i installed topmeni-gtk2 and topmenu-gtk3 both from standard repositories.

this is the output. 
note: you see:
`3/14 02:49:38| <type 'exceptions.KeyboardInterrupt'>: `
afer i pressed `<CTRL>C`.

note 2: sni-qt package is installed.

during the execution python reach the 17% of cpu. (i7-6700K)
Hoping helps to understand the issue.
David

```
davide@thor:~/bin/vintel/src$ python ./vintel.py 
03/14 02:49:05| 
03/14 02:49:05| ------------------- Vintel 1.1.2 starting up -------------------
03/14 02:49:05| 
"sni-qt/21773" WARN  14:49:05.494 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
03/14 02:49:05| 'MainWindow' object has no attribute 'changeClipboard'
03/14 02:49:05| 'MainWindow' object has no attribute 'changeFloatingOverview'
03/14 02:49:05| 'MainWindow' object has no attribute 'changeAlreadyShowedSoundWarning'
03/14 02:49:06| Load jump bridges
03/14 02:49:06| Creating chat parser
^C03/14 02:49:38| -- Unhandled Exception --
03/14 02:49:38|   File "./vintel.py", line 127, in <module>
    mainWindow = viui.MainWindow(chatLogDirectory, trayIcon, backGroundColor)
  File "/home/davide/bin/vintel/src/vi/ui/viui.py", line 132, in __init__
    self.setupMap(True)
  File "/home/davide/bin/vintel/src/vi/ui/viui.py", line 246, in setupMap
    self.chatparser = chatparser.ChatParser(self.pathToLogs, self.roomnames, self.systems)
  File "/home/davide/bin/vintel/src/vi/chatparser/chatparser.py", line 49, in __init__
    self._collectInitFileData(path)
  File "/home/davide/bin/vintel/src/vi/chatparser/chatparser.py", line 56, in _collectInitFileData
    fileTime = os.path.getmtime(fullPath)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime

03/14 02:49:38| <type 'exceptions.KeyboardInterrupt'>: 
03/14 02:49:38| -- ------------------- --
```

**Comment by Xanthos-Eve** [comment]
The initial warning looks like a message about sound - do you have pyglet installed? The rest looks like an exception generated when you typed <ctrl>C. That's expected. Vintel does a lot of work on startup. Downloading things and adding annotations to the SVG map. 17% is expected. On the Mac I see it spike to 30 - 50% and then it calms down to around 10%.

**Comment by Tetractys** [comment]
yes python-pyglet installed from repos ver 1.1.4 but it remains stuck at this:

```
davide@thor:~/bin/vintel/src$ python ./vintel.py 
03/14 03:19:06| 
03/14 03:19:06| ------------------- Vintel 1.1.2 starting up -------------------
03/14 03:19:06| 
"sni-qt/26230" WARN  15:19:06.291 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
03/14 03:19:06| 'MainWindow' object has no attribute 'changeClipboard'
03/14 03:19:06| 'MainWindow' object has no attribute 'changeFloatingOverview'
03/14 03:19:06| 'MainWindow' object has no attribute 'changeAlreadyShowedSoundWarning'
03/14 03:19:06| Load jump bridges
03/14 03:19:07| Creating chat parser


```
Vintel 1.0.0 runs correctly
Have you any test i can try?

**Comment by Xanthos-Eve** [comment]
Searching around the Inter-webs, looks like this is a sound subsystem problem. Pyglet 1.2.4 is what I am using btw. Little has changed with respect to sound, except some logging changes. I am planning to instal Linux on my machine with Fusion but not right away. Until then, it would help If you can step through the code with PyCharm - you may be able to track down the problem.

**Comment by Tetractys** [comment]
Since i just installed PyCharm 5.0.4 Community and Checkedout Vintel project from GitHub, i'm guessing if you can share with me your "settings" for the project.... (never used PyCharm but reopening the checkedout project i have no more organized views!) thanks in advance! if you need my email i'll give you. Or probably you can find it in my GitHub profile.

**Comment by Tetractys** [comment]
ok! It starts. Probably found a path to understand why the program does not start like previous ver 1.0.0:
Look at the timestamps:

```
davide@thor:~/bin/vintel/src$ python2.7 ./vintel.py 
03/14 06:09:13| 
03/14 06:09:13| ------------------- Vintel 1.1.2 starting up -------------------
03/14 06:09:13| 
"sni-qt/18034" WARN  18:09:13.341 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
03/14 06:09:13| 'MainWindow' object has no attribute 'changeClipboard'
03/14 06:09:13| 'MainWindow' object has no attribute 'changeFloatingOverview'
03/14 06:09:13| 'MainWindow' object has no attribute 'changeAlreadyShowedSoundWarning'
03/14 06:09:14| Load jump bridges
03/14 06:09:14| Creating chat parser #<---------------------- start
03/14 06:12:11| Initializing contextual menus #<-------------------- end
03/14 06:12:12| Updating the map
03/14 06:12:12| Map setup complete


```
Close to 3 minutes to parse the chat!
Note: i never ever deleted my log folder. i have 10 years of various chatlog in there. 
Is it possible that the parser goes to evaluate all logs for TheCitadel etc?

**Comment by Xanthos-Eve** [comment]
Ha - yeah I just deleted 10+ years of logs. I recommend setting them aside in another folder if you think you might need them.

**Comment by Xanthos-Eve** [comment]
Just verified that Vintel spins through all files in the chat logs directory whenever it notices any change in the directory. I'm going to add an entry in the FAQ for this recommending that people prune their log folder.

**Comment by Xanthos-Eve** [comment]
Just saw your note about the settings - not sure where all it keeps them - I have enclosed mine that sits here: /Users/mark/code/vintel/.idea

[idea.zip](https://github.com/Xanthos-Eve/vintel/files/173071/idea.zip)

**Comment by Tetractys** [comment]
Thanks a lot for everything! I'll have in short time the project in PyCharm with your settings. :)
I would like to help in dev, i mean, at least i propose you if interested, to translate all strings from English into Italian. Is this a thing you eventually would like? If "yes" could be your possible answer, please indicate me youe policies and which file i'll have to modify (probably a second string file) and how you want me to add a Language selection dialog :)
PS: guessing if you are Xanthos of VOLT ally ingame... :) i'm in VOLT too :) in any case feel free to convo me anytime! [VOLT|FA.ST] Tetractys

**Comment by Tetractys** [comment]
Anyway, deleting all logs but 2016 related, still program took 36 seconds to start. Since logs to file is enabled in EvE by default many users could suffer for this slowness.
Guessing what is the point to parse all old chatlogs when the needing is to parse only those are in "realtime" (so just the lasts created when the eveclient starts)... maybe could be useful to scan programmatically the directory Chatlogs and read *only* the newest... what do you think?

**Comment by Xanthos-Eve** [comment]
Feel free to experiment. Notice the comment at the top of filewatcher.py. Getting this to work reliably was a little tricky. I wonder if there is a way to ask the directory which files have changed? 
Another thing we can do is count the files before we start iterating over them. If there are many we throw up a dialog telling the user that its going to take a while to parse them all and suggest they move them out of the way.
Either way I'll dig into the APIs and do some googling  to see if there is something that can help us.

**Comment by Xanthos-Eve** [comment]
BTW if you want to do the translations we will need to do a little bit of prep work - we will need to move the strings into a string file, or which we will have one for each language supported and then we need to detect the language or follow a program setting to provide the right string at runtime. A way to support this via the community is to put all the strings in a column of a google sheet and then provide columns for different languages then invite the community to fill in the translations.

**Comment by Tetractys** [comment]
hi! guessing if i can see the code of the version 1.0.0. Seems to me very efficient. Unless you want to change something about the file management part i need to know, please, why you want to change the 1..0.0. code.
This is the best advice i found: http://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python 
Let me know. 

For the translation, multiple xml files (one each language - so you can send only that file to the translators) could do the work. 
Note: i'm not completely in to the python programming, but after decades of system management/admin i can have the "sense". Anyway i'll try to do my best for the project. :)
Cheers.

**Comment by Xanthos-Eve** [comment]
There are comments in the file watcher about problems on different
platforms. Whatever we do in there we need to test thoroughly. Watching the
directory for changes lets us know that "something" has changed - if only
we didn't have to spin through the file mod dates to find it.

Yes strings files for the program - I only mention the spreadsheet as a way
to get community contribution to do the translations. Better yet is a
centralized localization platform like http://pootle.translatehouse.org

**Comment by Xanthos-Eve** [comment]
No action on this in a while - is this still an issue for you @Tetractys ? We recently cut over to Six and Requests. Give it a go and see if any of these things have changed the situation at all.
