### ISSUE TITLE
Alarm Distance config should be on the Menu bar too

### ISSUE THREAD

**Issue by simonlinj** [Xanthos-Eve/vintel#69]
Currently the "right click on white area of the map" to configure the Alarm Distance is not very intuitive... Please have that option under "Sound" menu too...    

1 way to simplify is to combine with "Activated Sound" with select 1 menu

```
Menu -> Sound -> Activated Sound Alarm ->
   * Disabled
   0 Jumps
   1 Jumps
   2 Jumps
   3 Jumps
```

fly safe o7

**Comment by Xanthos-Eve** [comment]
I like it. Planning to redo all the menus and settings this next release.

**Comment by simonlinj** [comment]
Have no idea how to program with python and GUI. otherwise I could help! 

thanks for the tool! keep it coming!

**Comment by simonlinj** [comment]
the volume is relatively too loud.. probably would be nice to able to adjust the alarm volume as well.

**Comment by Xanthos-Eve** [comment]
Good call
