### ISSUE TITLE
Wrong map info

### ISSUE THREAD

**Issue by simonlinj** [Xanthos-Eve/vintel#74]
wrong map stargate info in F9E-KX system

![map2](https://cloud.githubusercontent.com/assets/1506890/15003876/a07690fe-117e-11e6-8b4c-aaae8faaed7f.png)

![map](https://cloud.githubusercontent.com/assets/1506890/15003877/a07bab0c-117e-11e6-8321-803fd8273727.png)

**Comment by Xanthos-Eve** [comment]
Thanks- a fix will be out shortly.
