### ISSUE TITLE
Jumpbridge file not loading from local disk

### ISSUE THREAD

**Issue by Bazzek** [Xanthos-Eve/vintel#85]
With version 1.1.3 (which is displaying 1.2.0-SNAPSHOT btw) the jumpbridge file will not load from my local disk anymore.

I get the error :
![capture](https://cloud.githubusercontent.com/assets/11552651/16355789/079006e0-3ac3-11e6-8b60-8f1dd9955810.PNG)

The file does exist and worked in 1.1.2

**Comment by Xanthos-Eve** [comment]
Interesting - nothing changed in that area. Fixing he version now.

**Comment by Xanthos-Eve** [comment]
what version of windows are you running? @Bazzek

**Comment by Xanthos-Eve** [comment]
This looks like it may be due to the switch over to using the Requests module. I'll look into it but its not a priority unless you really need to load your own jbs. Is this for a region other than catch or provi? I ask because I maintain the jb list for those regions.

**Comment by Xanthos-Eve** [comment]
Due to the Requests module not supporting the file:// scheme. Since there are ways around this - store the file on a cloud based service or a local web server - I dont intend to fix this.

**Comment by Xanthos-Eve** [comment]
I have updated the UI, dropping the file based example.
