### ISSUE TITLE
at start up 

### ISSUE THREAD

**Issue by tturini** [Xanthos-Eve/vintel#88]
popup an error, same for vers: 1.1.3 or 1.2.1, instead 1.1.2 it's ok
![image](https://cloud.githubusercontent.com/assets/20153825/16363348/c3913260-3bc7-11e6-996e-81fba9fc8f5e.png)

**Comment by Xanthos-Eve** [comment]
Assuming you are on a windows computer. We recently changed the way Vintel is built and may be missing some of the windows dlls. Many computers will have these from installation of other products or by downloading them from M$. I may be able to force load them in the build process.

**Comment by Xanthos-Eve** [comment]
This is an issue introduced by pyinstaller:
https://github.com/pyinstaller/pyinstaller/issues/1974

Possible workaround here: http://www.tomshardware.com/answers/id-2417960/msvcr100-dll-32bit-64bit.html

**Comment by Xanthos-Eve** [comment]
https://www.microsoft.com/en-in/download/details.aspx?id=5555

**Comment by tturini** [comment]
all done, x86 package fixed the matter, thanks :)
