### ISSUE TITLE
Alarm Distance

### ISSUE THREAD

**Issue by sys** [Xanthos-Eve/vintel#98]
Alarm distance is not saving in version 1.2.2. Have to set alarm distance on each launch.

**Comment by 3vi1** [comment]
I believe this might be related to https://github.com/Xanthos-Eve/vintel/issues/95.

Does the tray icon show the right distance after you start?  I think it *is* saving, but it's not initializing the menu on the webview properly.

**Comment by sys** [comment]
Yes. So this is duplicate report. Sorry for that. 
In tray ( right click ) menu it shows correct distance while in the main screen on right click it shows 0 alarm distance.

**Comment by 3vi1** [comment]
No worries!  At first glance, the code looks fine... but there might be some considerations with the webview context menus that I am unaware of.  If Xanthos or one of the other devs doesn't beat me to it, I'll see if I can puzzle it out tomorrow.
