### ISSUE TITLE
TBD:  Sound not being closed properly?

### ISSUE THREAD

**Issue by 3vi1** [Xanthos-Eve/vintel#99]
![image](https://cloud.githubusercontent.com/assets/628806/16537943/47fb5a6c-3fd8-11e6-9ae8-b66419deee67.png)

**Comment by Xanthos-Eve** [comment]
Please check the vintel log and try to determine if those are due to the app crashing or hitting an unhanded exception or whether its due to the normal shutdown.

**Comment by Xanthos-Eve** [comment]
Yes there was an exception being thrown - refactored thread shutdown for good!
